web:
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - ./source:/source
        - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ./source:/source
